FROM alpine:3 AS base
WORKDIR /app

FROM golang:1.20-alpine AS build

WORKDIR /src
COPY . .

WORKDIR src/master
RUN go build -o /app/master

FROM base AS final
WORKDIR /app
COPY --from=build /app/master /app/master

CMD [ "/app/master" ]