FROM alpine:3 AS base
WORKDIR /app

FROM golang:1.17-alpine AS build

WORKDIR /src
COPY . .

WORKDIR src/worker
RUN go build -o /app/worker

FROM base AS final
WORKDIR /app
COPY --from=build /app/worker /app/worker

CMD [ "/app/worker" ]